language: node_js
node_js:
  - "0.10"

services:
  - postgresql
  
addons:
  postgresql: "9.3"

install:
  - cd LilyPadBackend/
  - npm install
  - psql -c 'create database test;' -U postgres
  - cd models/postgres/
  - psql -f init.sql -U postgres
  - cd ../..
  
script:
  - npm test
